const Images = {
  logo: () => require("./logo.png"),
  background1: () => require("./backround1.jpg"),
  whatsApp: () => require("./whatsapp.png"),
  codezoneBI1: () => require("./codezoneBI1.png"),
  codeZoneBT2: () => require("./codezoneBI2.png"),
  user: () => require("./user.png"),
  groups: () => require("./groups.png"),
  sandWatch: () => require("./sandwatch.png"),
  checkMark: () => require("./check-mark.png"),
  lightBulb: () => require("./light_bulb.png"),
  examResult: () => require("./exam-results.png"),
  coding: () => require("./coding.png"),
  locations: () => require("./locations.png"),
  group: () => require("./group.png"),
  training: () => require("./training.png"),
  upload: () => require("./upload.png"),
  checkBox: () => require("./check-box.png"),
};
export default Images;
